In [3]:
import pandas as pd
df = pd.read_csv('super_dirty_students.csv')

In [4]:
df.head(10)

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,ninety,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,ninety,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
5,6,David Martinez,20,Male,ninety,001-074-828-6016x937,Hugheshaven,nathangibbs@hotmail.com,1603493647,DATA SCIENCE,110,pending,15.5,average,"85,00",1983-04-30T01:46:36,"Apartment 42, North Jamesfurt district, Tashke...","{hobbies:['order', 'keep']}"
6,7,NaN,18 years,FEMALE,71,314.018.0928x3134,Sharpfurt,nguyenlisa@@horn.org,1982-01-16,data science,NaN,active,0,excellent,275.0,19/11/2004 11:42 PM,"Lake Tracishire 29-kv, dom 8, Tashkent","{'hobbies': ['fall', 'teacher'], 'skills': {'t..."
7,8,Nicholas Dennis,21,FEMALE,ninety,8091556011,Matthewfort,avoid,2000.06.26,python,63,active,four point five,excellent,135,1978/09/23,"70576 Butler Harbor Suite 847, Janetberg",INVALID_JSON_DATA
8,9,NaN,twenty,fmale,77,854-964-5423,South Paulchester,stacysmith@taylor.biz,2000-03-15,ds,110%,active,15.5,excellent,104 USD,1995-10-20,"Williamsborough 2-kv, dom 18, Tashkent","{'hobbies': ['require', 'open'], 'skills': {'t..."
9,10,Elizabeth Villegas,22,femlae,NaN,(205)467-4476x0583,South Dianatown,anthonywalker@@gmail.com,2013-02-11T07:12:29,data_sciense,99,inactive,"3,7",average,"215,00",2014-12-16T06:44:51,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['management', 'to'], 'skills': {'..."

In [5]:
type(df)

pandas.DataFrame

In [6]:
df.columns

Index(['student_id', 'name', 'age', 'gender', 'score', 'phone', 'city',
       'email', 'date_of_join', 'course', 'attendance', 'status', 'gpa',
       'remarks', 'money_spent', 'event_time', 'address_raw', 'profile_json'],
      dtype='str')

In [7]:
df.isna().sum()

student_id        0
name            335
age             108
gender          219
score           246
phone           371
city              0
email           151
date_of_join      0
course            0
attendance      326
status            0
gpa             141
remarks         204
money_spent       0
event_time        0
address_raw       0
profile_json      0
dtype: int64

In [8]:
df.dtypes

student_id      int64
name              str
age               str
gender            str
score             str
phone             str
city              str
email             str
date_of_join      str
course            str
attendance        str
status            str
gpa               str
remarks           str
money_spent       str
event_time        str
address_raw       str
profile_json      str
dtype: object

In [9]:
columns = df.select_dtypes(include=[object]).columns
for column in columns:
    df[column] = df[column].str.strip()

C:\Users\ASUS\AppData\Local\Temp\ipykernel_25052\2642288721.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  columns = df.select_dtypes(include=[object]).columns

In [10]:
df.fillna('NaN')

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,ninety,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,ninety,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,twenty,fmale,81,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992.11.13,DATA SCIENCE,NaN,inactive,NaN,excellent,$64,14/10/2007 06:53 PM,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024.10.05,DATA SCIENCE,NaN,pending,"3,7",NaN,143,2021-06-21T07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,19/11/2021 02:23 AM,data_sciense,95,inactive,-2,excellent,79.0,1975/05/11,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,1625723463,data_sciense,110%,active,3.06,average,"238,00",2015.05.24,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,twenty,NaN,ninety,486.754.8735,Dariusborough,?ali@@gmail..com,1624533231,PYTHNO,70,inactive,four point five,excellent,224.0,27/06/2015 08:04 AM,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [11]:
df['age'] = df['age'].replace('twenty', '20')
df['age'] = df['age'].str.replace('years', '')
df['age']

0      20
1      20
2      20
3      20
4      20
       ..
995    22
996    20
997    20
998    21
999    20
Name: age, Length: 1000, dtype: str

In [12]:
df['age']

0      20
1      20
2      20
3      20
4      20
       ..
995    22
996    20
997    20
998    21
999    20
Name: age, Length: 1000, dtype: str

In [13]:
df['score'] = df['score'].replace('ninety', '90')
df['score'] = df['score'].astype(float)
df['score']

0       NaN
1      90.0
2      90.0
3      81.0
4       NaN
       ...
995     NaN
996     NaN
997     NaN
998    86.0
999    90.0
Name: score, Length: 1000, dtype: float64

In [14]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992.11.13,DATA SCIENCE,NaN,inactive,NaN,excellent,$64,14/10/2007 06:53 PM,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024.10.05,DATA SCIENCE,NaN,pending,"3,7",NaN,143,2021-06-21T07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,19/11/2021 02:23 AM,data_sciense,95,inactive,-2,excellent,79.0,1975/05/11,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,1625723463,data_sciense,110%,active,3.06,average,"238,00",2015.05.24,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,20,NaN,90.0,486.754.8735,Dariusborough,?ali@@gmail..com,1624533231,PYTHNO,70,inactive,four point five,excellent,224.0,27/06/2015 08:04 AM,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [15]:
df['gpa'] = df['gpa'].replace('four point five', '4.5')
df['gpa'] = df['gpa'].str.replace(',', '.')
df['gpa'] = df['gpa'].astype(float)

In [16]:
df['gpa']

0      3.72
1      1.88
2       NaN
3      0.00
4      4.37
       ...
995     NaN
996    3.70
997   -2.00
998    3.06
999    4.50
Name: gpa, Length: 1000, dtype: float64

In [17]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0.00,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992.11.13,DATA SCIENCE,NaN,inactive,NaN,excellent,$64,14/10/2007 06:53 PM,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024.10.05,DATA SCIENCE,NaN,pending,3.70,NaN,143,2021-06-21T07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,19/11/2021 02:23 AM,data_sciense,95,inactive,-2.00,excellent,79.0,1975/05/11,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,1625723463,data_sciense,110%,active,3.06,average,"238,00",2015.05.24,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,20,NaN,90.0,486.754.8735,Dariusborough,?ali@@gmail..com,1624533231,PYTHNO,70,inactive,4.50,excellent,224.0,27/06/2015 08:04 AM,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [18]:
df['attendance'] = df['attendance'].str.strip('%')
df['attendance'] = df['attendance'].astype(float)

In [19]:
df['attendance']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
       ...
995      NaN
996      NaN
997     95.0
998    110.0
999     70.0
Name: attendance, Length: 1000, dtype: float64

In [20]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,$135,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,$152,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0.00,good,175 USD,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,$282,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992.11.13,DATA SCIENCE,NaN,inactive,NaN,excellent,$64,14/10/2007 06:53 PM,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024.10.05,DATA SCIENCE,NaN,pending,3.70,NaN,143,2021-06-21T07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,19/11/2021 02:23 AM,data_sciense,95.0,inactive,-2.00,excellent,79.0,1975/05/11,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,1625723463,data_sciense,110.0,active,3.06,average,"238,00",2015.05.24,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,20,NaN,90.0,486.754.8735,Dariusborough,?ali@@gmail..com,1624533231,PYTHNO,70.0,inactive,4.50,excellent,224.0,27/06/2015 08:04 AM,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [21]:
df['money_spent'] = df['money_spent'].str.strip('$')
df['money_spent'] = df['money_spent'].str.replace('USD', '')
df['money_spent'] = df['money_spent'].str.replace(',', '.')
df['money_spent'] = df['money_spent'].astype(float)
df['money_spent']

0      135.0
1      152.0
2      185.0
3      175.0
4      282.0
       ...
995     64.0
996    143.0
997     79.0
998    238.0
999    224.0
Name: money_spent, Length: 1000, dtype: float64

In [22]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,1662247364,Data Science,NaN,active,3.72,good,135.0,1629312830,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017/08/29,Data Science,NaN,active,1.88,excellent,152.0,11/10/2001 04:19 AM,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,1657837622,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17,data-sciens,NaN,inactive,0.00,good,175.0,1682795130,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023/11/25,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992.11.13,DATA SCIENCE,NaN,inactive,NaN,excellent,64.0,14/10/2007 06:53 PM,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024.10.05,DATA SCIENCE,NaN,pending,3.70,NaN,143.0,2021-06-21T07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,19/11/2021 02:23 AM,data_sciense,95.0,inactive,-2.00,excellent,79.0,1975/05/11,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,1625723463,data_sciense,110.0,active,3.06,average,238.0,2015.05.24,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,20,NaN,90.0,486.754.8735,Dariusborough,?ali@@gmail..com,1624533231,PYTHNO,70.0,inactive,4.50,excellent,224.0,27/06/2015 08:04 AM,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [23]:
def convert_to(value):
    try:
        return pd.to_datetime(float(value), unit='s')
    except:
        return pd.to_datetime(value)
df['date_of_join'] = df['date_of_join'].apply(convert_to)
df['event_time'] = df['event_time'].apply(convert_to)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_25052\3717870133.py:5: UserWarning: Parsing dates in %d/%m/%Y %I:%M %p format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(value)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_25052\3717870133.py:5: UserWarning: Parsing dates in %d/%m/%Y %I:%M %p format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(value)

In [24]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,someonegmail.com,2022-09-03 23:22:44,Data Science,NaN,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,special,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,six,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,NaN,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,NaN,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,someonegmail.com,2021-11-19 02:23:00,data_sciense,95.0,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,001-663-118-1327x207,Port Rachael,richardgreen@@shannon-jenkins.info,2021-07-08 05:51:03,data_sciense,110.0,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,20,NaN,90.0,486.754.8735,Dariusborough,?ali@@gmail..com,2021-06-24 11:13:51,PYTHNO,70.0,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [25]:
df['email'] = df['email'].str.lower().str.strip()
df['email'] = df['email'].str.replace('@@', '@')
df['email'] = df['email'].str.replace('..', '.')
df['email'] = df['email'].str.replace('-', '')
df['email'] = df['email'].str.strip('?')
pattern = r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'

df.loc[~df["email"].str.match(pattern, na=False), "email"] = None

In [26]:
df['email']

0                                   NaN
1                       psmith@chen.com
2                                   NaN
3                                   NaN
4                                   NaN
                     ...
995                   amy97@woodard.net
996               katiepage@hensley.com
997                                 NaN
998    richardgreen@shannonjenkins.info
999                       ali@gmail.com
Name: email, Length: 1000, dtype: str

In [27]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152x102,Katieland,NaN,2022-09-03 23:22:44,Data Science,NaN,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,001-182-659-5631x02803,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,NaN,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,001-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,NaN,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,264-577-8585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,95.0,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,001-663-118-1327x207,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,data_sciense,110.0,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,20,NaN,90.0,486.754.8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,PYTHNO,70.0,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [28]:
df["phone"] = df["phone"].str.replace(r'x\d+', '', regex=True)
df['phone'] = df['phone'].str.replace('[^0-9]', '', regex=True)
df['phone'] = df['phone'].str[-10:]
df.loc[df['phone'].str.len() != 10, 'phone'] = None
df['phone'] = df['phone'].apply(lambda x: f'+1-{x[0:3]}-{x[3:6]}-{x[6:10]}' if pd.notnull(x) else None)

In [29]:
df['phone']

0      +1-619-379-4152
1                  NaN
2                  NaN
3                  NaN
4      +1-182-659-5631
            ...
995                NaN
996    +1-205-065-8737
997    +1-264-577-8585
998    +1-663-118-1327
999    +1-486-754-8735
Name: phone, Length: 1000, dtype: str

In [30]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,attendance,status,gpa,remarks,money_spent,event_time,address_raw,profile_json
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data Science,NaN,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,NaN,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}"
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,NaN,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,NaN,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,NaN,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,NaN,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,NaN,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,NaN,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA
997,998,NaN,20,MALE,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,95.0,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,FEMALE,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,data_sciense,110.0,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,20,NaN,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,PYTHNO,70.0,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA

In [31]:
df[['addr_city', 'addr_district', 'addr_postal']] = None

df['addr_postal'] = df['address_raw'].str.extract(r'(\b\d{6}\b)')
df['addr_city'] = df['address_raw'].str.extract(r'(Tashkent)')

df['addr_district'] = df['address_raw'].str.extract(r'([A-Za-z\s]+)\s+district')

df.loc[df['addr_district'].isna(), 'addr_district'] = (df['address_raw'].str.extract(r'Tashkent\s+([A-Za-z\s]+)'))

# df = df[~df['address_raw'].str.contains('BROKEN', na=False)]
df.loc[df['address_raw'].str.contains('BROKEN', na=False),
       ['addr_city', 'addr_district', 'addr_postal']] = None

In [32]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,status,gpa,remarks,money_spent,event_time,address_raw,profile_json,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data Science,...,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'...",Tashkent,South Kevin,100539
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}",Tashkent,NaN,100332
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t...",Tashkent,NaN,NaN
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech...",Tashkent,North Tamara,100097
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {...",Tashkent,Laurenhaven,100254
996,997,Scott Clark,20,NaN,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,...,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA,Tashkent,NaN,NaN
997,998,NaN,20,MALE,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,...,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te...",Tashkent,New Brendan,100394
998,999,Brittany Barrett,21,FEMALE,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,data_sciense,...,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec...",NaN,NaN,NaN
999,1000,NaN,20,NaN,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,PYTHNO,...,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA,Tashkent,Grossbury,100222

In [33]:
# df.duplicated()
# df = df.drop_duplicates()

In [34]:
df.shape

(1000, 21)

In [35]:
df.isna().sum()

student_id         0
name             335
age              108
gender           219
score            246
phone            371
city               0
email            422
date_of_join       0
course             0
attendance       326
status             0
gpa              141
remarks          204
money_spent        0
event_time         0
address_raw        0
profile_json       0
addr_city        430
addr_district    797
addr_postal      603
dtype: int64

In [36]:
important_columns = ['student_id', 'name', 'age', 'gender', 'course', 'score', 'attendance', 'status']
df[important_columns].isna().sum()

student_id      0
name          335
age           108
gender        219
course          0
score         246
attendance    326
status          0
dtype: int64

In [37]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,status,gpa,remarks,money_spent,event_time,address_raw,profile_json,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,NaN,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data Science,...,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'...",Tashkent,South Kevin,100539
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}",Tashkent,NaN,100332
2,3,Kathryn Moyer,20,NaN,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t...",Tashkent,NaN,NaN
3,4,Ruben Wilson,20,fmale,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech...",Tashkent,North Tamara,100097
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,fmale,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {...",Tashkent,Laurenhaven,100254
996,997,Scott Clark,20,NaN,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,...,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA,Tashkent,NaN,NaN
997,998,NaN,20,MALE,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,...,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te...",Tashkent,New Brendan,100394
998,999,Brittany Barrett,21,FEMALE,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,data_sciense,...,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec...",NaN,NaN,NaN
999,1000,NaN,20,NaN,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,PYTHNO,...,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA,Tashkent,Grossbury,100222

In [38]:
df['gender'] = df['gender'].str.lower()
df['gender'] = df['gender'].str.replace('fmale', 'female')
df['gender'] = df['gender'].str.replace('femlae', 'female')
df['gender'] = df['gender'].str.capitalize()
df['gender'] = df['gender'].fillna('Unknown')
df['gender']

0      Unknown
1       Female
2      Unknown
3       Female
4       Female
        ...
995     Female
996    Unknown
997       Male
998     Female
999    Unknown
Name: gender, Length: 1000, dtype: str

In [39]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,status,gpa,remarks,money_spent,event_time,address_raw,profile_json,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,Unknown,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data Science,...,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'...",Tashkent,South Kevin,100539
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data Science,...,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}",Tashkent,NaN,100332
2,3,Kathryn Moyer,20,Unknown,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,DATA SCIENCE,...,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t...",Tashkent,NaN,NaN
3,4,Ruben Wilson,20,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,data-sciens,...,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech...",Tashkent,North Tamara,100097
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,data_sciense,...,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,DATA SCIENCE,...,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {...",Tashkent,Laurenhaven,100254
996,997,Scott Clark,20,Unknown,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,DATA SCIENCE,...,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA,Tashkent,NaN,NaN
997,998,NaN,20,Male,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,data_sciense,...,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te...",Tashkent,New Brendan,100394
998,999,Brittany Barrett,21,Female,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,data_sciense,...,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec...",NaN,NaN,NaN
999,1000,NaN,20,Unknown,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,PYTHNO,...,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA,Tashkent,Grossbury,100222

In [40]:
df['course'] = df['course'].str.lower()
df['course'] = df['course'].str.replace('ds', 'data science')
df['course'] = df['course'].str.replace('d.s.', 'data science')
df['course'] = df['course'].str.replace('data-sciens', 'data science')
df['course'] = df['course'].str.replace('pythno', 'python')
df['course'] = df['course'].str.replace('pyhton', 'python')
df['course'] = df['course'].str.capitalize()
df['course'] = df['course'].fillna('Other')
df['course']

0      Data science
1      Data science
2      Data science
3      Data science
4      Data_sciense
           ...
995    Data science
996    Data science
997    Data_sciense
998    Data_sciense
999          Python
Name: course, Length: 1000, dtype: str

In [41]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,status,gpa,remarks,money_spent,event_time,address_raw,profile_json,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,Unknown,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data science,...,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'...",Tashkent,South Kevin,100539
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data science,...,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}",Tashkent,NaN,100332
2,3,Kathryn Moyer,20,Unknown,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,Data science,...,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t...",Tashkent,NaN,NaN
3,4,Ruben Wilson,20,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,Data science,...,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech...",Tashkent,North Tamara,100097
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,Data_sciense,...,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,Data science,...,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {...",Tashkent,Laurenhaven,100254
996,997,Scott Clark,20,Unknown,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,Data science,...,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA,Tashkent,NaN,NaN
997,998,NaN,20,Male,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,Data_sciense,...,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te...",Tashkent,New Brendan,100394
998,999,Brittany Barrett,21,Female,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,Data_sciense,...,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec...",NaN,NaN,NaN
999,1000,NaN,20,Unknown,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,Python,...,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA,Tashkent,Grossbury,100222

In [42]:
df['status'] = df['status'].str.lower()

In [43]:
df.dtypes

student_id                int64
name                        str
age                         str
gender                      str
score                   float64
phone                       str
city                        str
email                       str
date_of_join     datetime64[us]
course                      str
attendance              float64
status                      str
gpa                     float64
remarks                     str
money_spent             float64
event_time       datetime64[us]
address_raw                 str
profile_json                str
addr_city                   str
addr_district               str
addr_postal                 str
dtype: object

In [44]:
df['age'] = df['age'].fillna('0')
df['age'] = df['age'].astype(int)

In [45]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,status,gpa,remarks,money_spent,event_time,address_raw,profile_json,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,Unknown,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data science,...,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'...",Tashkent,South Kevin,100539
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data science,...,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}",Tashkent,NaN,100332
2,3,Kathryn Moyer,20,Unknown,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,Data science,...,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t...",Tashkent,NaN,NaN
3,4,Ruben Wilson,20,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,Data science,...,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech...",Tashkent,North Tamara,100097
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,Data_sciense,...,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,Data science,...,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {...",Tashkent,Laurenhaven,100254
996,997,Scott Clark,20,Unknown,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,Data science,...,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA,Tashkent,NaN,NaN
997,998,NaN,20,Male,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,Data_sciense,...,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te...",Tashkent,New Brendan,100394
998,999,Brittany Barrett,21,Female,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,Data_sciense,...,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec...",NaN,NaN,NaN
999,1000,NaN,20,Unknown,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,Python,...,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA,Tashkent,Grossbury,100222

In [46]:
df.shape

(1000, 21)

In [47]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,status,gpa,remarks,money_spent,event_time,address_raw,profile_json,addr_city,addr_district,addr_postal
0,1,Claudia Short,20,Unknown,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data science,...,active,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{'hobbies': ['gun', 'nice'], 'skills': {'tech'...",Tashkent,South Kevin,100539
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data science,...,active,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{hobbies:['against', 'good']}",Tashkent,NaN,100332
2,3,Kathryn Moyer,20,Unknown,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,Data science,...,pending,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{'hobbies': ['fast', 'clearly'], 'skills': {'t...",Tashkent,NaN,NaN
3,4,Ruben Wilson,20,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,Data science,...,inactive,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{'hobbies': ['left', 'role'], 'skills': {'tech...",Tashkent,North Tamara,100097
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,Data_sciense,...,pending,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{'hobbies': ['sort', 'science'], 'skills': {'t...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,Data science,...,inactive,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{'hobbies': ['collection', 'his'], 'skills': {...",Tashkent,Laurenhaven,100254
996,997,Scott Clark,20,Unknown,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,Data science,...,pending,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",INVALID_JSON_DATA,Tashkent,NaN,NaN
997,998,NaN,20,Male,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,Data_sciense,...,inactive,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{'hobbies': ['street', 'read'], 'skills': {'te...",Tashkent,New Brendan,100394
998,999,Brittany Barrett,21,Female,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,Data_sciense,...,active,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{'hobbies': ['game', 'total'], 'skills': {'tec...",NaN,NaN,NaN
999,1000,NaN,20,Unknown,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,Python,...,inactive,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",INVALID_JSON_DATA,Tashkent,Grossbury,100222

In [48]:
import json
df['profile_json'] = df['profile_json'].str.replace("'", '"')
df['profile_json'] = df['profile_json'].str.replace('INVALID_JSON_DATA', '')
df['profile_json'] = df['profile_json'].str.replace('{hobbies', '{"hobbies"')

def load_json(x):
    if pd.isna(x) or str(x).strip() == "":
        return None
    try:
        return json.loads(x)
    except:
        return None

df['parsed_json'] = df['profile_json'].apply(load_json)

In [49]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,gpa,remarks,money_spent,event_time,address_raw,profile_json,addr_city,addr_district,addr_postal,parsed_json
0,1,Claudia Short,20,Unknown,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data science,...,3.72,good,135.0,2021-08-18 18:53:50,"Apartment 37, South Kevin district, Tashkent, ...","{""hobbies"": [""gun"", ""nice""], ""skills"": {""tech""...",Tashkent,South Kevin,100539,"{'hobbies': ['gun', 'nice'], 'skills': {'tech'..."
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data science,...,1.88,excellent,152.0,2001-11-10 04:19:00,UZ 100332 Tashkent South Patricia,"{""hobbies"":[""against"", ""good""]}",Tashkent,NaN,100332,"{'hobbies': ['against', 'good']}"
2,3,Kathryn Moyer,20,Unknown,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,Data science,...,NaN,excellent,185.0,2022-07-14 22:27:02,"Wendyshire 12-kv, dom 1, Tashkent","{""hobbies"": [""fast"", ""clearly""], ""skills"": {""t...",Tashkent,NaN,NaN,"{'hobbies': ['fast', 'clearly'], 'skills': {'t..."
3,4,Ruben Wilson,20,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,Data science,...,0.00,good,175.0,2023-04-29 19:05:30,"Apartment 16, North Tamara district, Tashkent,...","{""hobbies"": [""left"", ""role""], ""skills"": {""tech...",Tashkent,North Tamara,100097,"{'hobbies': ['left', 'role'], 'skills': {'tech..."
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,Data_sciense,...,4.37,average,282.0,2013-10-13 00:00:00,"BROKEN,ADDRESS,DATA,,,","{""hobbies"": [""sort"", ""science""], ""skills"": {""t...",NaN,NaN,NaN,"{'hobbies': ['sort', 'science'], 'skills': {'t..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,Data science,...,NaN,excellent,64.0,2007-10-14 18:53:00,"Apartment 12, Laurenhaven district, Tashkent, ...","{""hobbies"": [""collection"", ""his""], ""skills"": {...",Tashkent,Laurenhaven,100254,"{'hobbies': ['collection', 'his'], 'skills': {..."
996,997,Scott Clark,20,Unknown,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,Data science,...,3.70,NaN,143.0,2021-06-21 07:46:27,"Patrickmouth 4-kv, dom 6, Tashkent",,Tashkent,NaN,NaN,None
997,998,NaN,20,Male,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,Data_sciense,...,-2.00,excellent,79.0,1975-05-11 00:00:00,"Apartment 38, New Brendan district, Tashkent, ...","{""hobbies"": [""street"", ""read""], ""skills"": {""te...",Tashkent,New Brendan,100394,"{'hobbies': ['street', 'read'], 'skills': {'te..."
998,999,Brittany Barrett,21,Female,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,Data_sciense,...,3.06,average,238.0,2015-05-24 00:00:00,"25998 Martinez Grove Apt. 473, West Scott","{""hobbies"": [""game"", ""total""], ""skills"": {""tec...",NaN,NaN,NaN,"{'hobbies': ['game', 'total'], 'skills': {'tec..."
999,1000,NaN,20,Unknown,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,Python,...,4.50,excellent,224.0,2015-06-27 08:04:00,"Apartment 24, Grossbury district, Tashkent, UZ...",,Tashkent,Grossbury,100222,None

In [50]:
df_new = pd.json_normalize(
    df[df['parsed_json'].notna()]['parsed_json']
)

In [51]:
df_new

,hobbies,devices,skills.tech.python,skills.tech.excel,skills.tech.sql,skills.soft,family.siblings,family.income.father,family.income.mother
0,"[gun, nice]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",2.0,5.0,1.0,"[with, onto]",4.0,1198.0,1089.0
1,"[against, good]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[fast, clearly]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",5.0,3.0,1.0,"[despite, clearly]",1.0,263.0,202.0
3,"[left, role]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",3.0,5.0,1.0,"[full, series]",4.0,508.0,698.0
4,"[sort, science]","[{'type': 'laptop', 'brand': 'Lenovo', 'year':...",1.0,4.0,1.0,"[whose, save]",3.0,862.0,1058.0
...,...,...,...,...,...,...,...,...,...
992,"[address, feel]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,"[understand, support]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,"[collection, his]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",3.0,5.0,1.0,"[increase, everything]",5.0,1382.0,1335.0
997,"[street, read]","[{'type': 'laptop', 'brand': 'HP', 'year': 202...",1.0,4.0,4.0,"[dinner, while]",5.0,1285.0,1005.0
998,"[game, total]","[{'type': 'laptop', 'brand': 'Dell', 'year': 2...",2.0,2.0,1.0,"[present, cup]",3.0,541.0,571.0

In [52]:
df_new['hobbies'] = df_new['hobbies'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)
df_new['skills.soft'] = df_new['skills.soft'].apply(lambda x: ','.join(x) if isinstance(x, list) else x)
# df_new['hobbies'] = df_new['hobbies'].astype(str)
# df_new['hobbies'] = df_new['hobbies'].str.strip('[]')
# df_new['hobbies']

In [53]:
df_new["devices"] = df_new["devices"].apply(lambda x: x if isinstance(x, list) else [])
dev_slots = df_new["devices"].apply(pd.Series)
dev_cols = []
for i in dev_slots.columns:
    series_i = dev_slots[i].apply(lambda v: v if isinstance(v, dict) else {})
    d = pd.json_normalize(series_i).add_prefix(f"device{i+1}_")
    dev_cols.append(d)
final = pd.concat([df_new.drop(columns=["devices"])] + dev_cols, axis=1)

In [54]:
df = pd.concat([df, final], axis=1)
# df_nonnull = df_new[df_new['devices'].notna()]
# df_exploded = df_nonnull.explode('devices')
# df_devices = pd.json_normalize(df_exploded['devices'])

In [55]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,skills.soft,family.siblings,family.income.father,family.income.mother,device1_type,device1_brand,device1_year,device2_type,device2_brand,device2_year
0,1,Claudia Short,20,Unknown,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data science,...,"with,onto",4.0,1198.0,1089.0,laptop,HP,2021.0,phone,Xiaomi,2021.0
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Kathryn Moyer,20,Unknown,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,Data science,...,"despite,clearly",1.0,263.0,202.0,laptop,HP,2020.0,phone,Samsung,2023.0
3,4,Ruben Wilson,20,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,Data science,...,"full,series",4.0,508.0,698.0,laptop,Lenovo,2020.0,phone,Samsung,2024.0
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,Data_sciense,...,"whose,save",3.0,862.0,1058.0,laptop,Lenovo,2023.0,phone,Apple,2022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,Data science,...,"increase,everything",5.0,1382.0,1335.0,laptop,Dell,2017.0,phone,Xiaomi,2019.0
996,997,Scott Clark,20,Unknown,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,Data science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,20,Male,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,Data_sciense,...,"dinner,while",5.0,1285.0,1005.0,laptop,HP,2020.0,phone,Xiaomi,2024.0
998,999,Brittany Barrett,21,Female,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,Data_sciense,...,"present,cup",3.0,541.0,571.0,laptop,Dell,2022.0,phone,Samsung,2019.0
999,1000,NaN,20,Unknown,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,Python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
df['email'].isna().sum()

np.int64(422)

In [57]:
df['phone'].isna().sum()

np.int64(371)

In [58]:
df.loc[~df["attendance"].between(1, 100), "attendance"] = None

In [59]:
df.loc[~df["gpa"].between(0, 5), "gpa"] = None

In [60]:
df.loc[~df["score"].between(0, 100), "score"] = None

In [61]:
df

,student_id,name,age,gender,score,phone,city,email,date_of_join,course,...,skills.soft,family.siblings,family.income.father,family.income.mother,device1_type,device1_brand,device1_year,device2_type,device2_brand,device2_year
0,1,Claudia Short,20,Unknown,NaN,+1-619-379-4152,Katieland,NaN,2022-09-03 23:22:44,Data science,...,"with,onto",4.0,1198.0,1089.0,laptop,HP,2021.0,phone,Xiaomi,2021.0
1,2,NaN,20,Female,90.0,NaN,Dawnburgh,psmith@chen.com,2017-08-29 00:00:00,Data science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Kathryn Moyer,20,Unknown,90.0,NaN,Lake Stevenmouth,NaN,2017-08-14 00:00:00,Data science,...,"despite,clearly",1.0,263.0,202.0,laptop,HP,2020.0,phone,Samsung,2023.0
3,4,Ruben Wilson,20,Female,81.0,NaN,Port Pamelafort,NaN,1973-09-17 00:00:00,Data science,...,"full,series",4.0,508.0,698.0,laptop,Lenovo,2020.0,phone,Samsung,2024.0
4,5,Robert Pruitt,20,Female,NaN,+1-182-659-5631,Kingburgh,NaN,2023-11-25 00:00:00,Data_sciense,...,"whose,save",3.0,862.0,1058.0,laptop,Lenovo,2023.0,phone,Apple,2022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Gary Sawyer,22,Female,NaN,NaN,Gabriellefurt,amy97@woodard.net,1992-11-13 00:00:00,Data science,...,"increase,everything",5.0,1382.0,1335.0,laptop,Dell,2017.0,phone,Xiaomi,2019.0
996,997,Scott Clark,20,Unknown,NaN,+1-205-065-8737,Rogerborough,katiepage@hensley.com,2024-10-05 00:00:00,Data science,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,998,NaN,20,Male,NaN,+1-264-577-8585,South Mary,NaN,2021-11-19 02:23:00,Data_sciense,...,"dinner,while",5.0,1285.0,1005.0,laptop,HP,2020.0,phone,Xiaomi,2024.0
998,999,Brittany Barrett,21,Female,86.0,+1-663-118-1327,Port Rachael,richardgreen@shannonjenkins.info,2021-07-08 05:51:03,Data_sciense,...,"present,cup",3.0,541.0,571.0,laptop,Dell,2022.0,phone,Samsung,2019.0
999,1000,NaN,20,Unknown,90.0,+1-486-754-8735,Dariusborough,ali@gmail.com,2021-06-24 11:13:51,Python,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df.to_csv("super_dirty_students_cleaned.csv")

In [63]:
df.dtypes

student_id                       int64
name                               str
age                              int64
gender                             str
score                          float64
phone                              str
city                               str
email                              str
date_of_join            datetime64[us]
course                             str
attendance                     float64
status                             str
gpa                            float64
remarks                            str
money_spent                    float64
event_time              datetime64[us]
address_raw                        str
profile_json                       str
addr_city                          str
addr_district                      str
addr_postal                        str
parsed_json                     object
hobbies                            str
skills.tech.python             float64
skills.tech.excel              float64
skills.tech.sql                float64
skills.soft                        str
family.siblings                float64
family.income.father           float64
family.income.mother           float64
device1_type                       str
device1_brand                      str
device1_year                   float64
device2_type                       str
device2_brand                      str
device2_year                   float64
dtype: object