In [18]:
import pandas as pd
df = pd.read_csv('data-engineer-interview-data (2).csv')

In [9]:
import pandas as pd

df["RefersToDocumentNumber"] = pd.to_numeric(df["RefersToDocumentNumber"], errors="coerce")
df["RefersToDocumentYear"] = pd.to_numeric(df["RefersToDocumentYear"], errors="coerce")

mask = (
    df["RefersToDocumentNumber"].between(1900, 2100, inclusive="both")
    & ~df["RefersToDocumentYear"].between(1900, 2100, inclusive="both")
    & df["RefersToDocumentYear"].notna()
)

print(df.loc[mask, ["RefersToDocumentNumber", "RefersToDocumentYear"]])

df.loc[mask, ["RefersToDocumentNumber", "RefersToDocumentYear"]] = (
    df.loc[mask, ["RefersToDocumentYear", "RefersToDocumentNumber"]].to_numpy()
)

print(df.loc[mask, ["RefersToDocumentNumber", "RefersToDocumentYear"]])

     RefersToDocumentNumber  RefersToDocumentYear
5                    2016.0                  98.0
6                    1992.0                  97.0
10                   2013.0                  84.0
11                   2002.0                 199.0
17                   2015.0                 130.0
19                   2015.0                  94.0
20                   2010.0                 100.0
24                   2013.0                 144.0
26                   2005.0                 115.0
27                   2013.0                  84.0
33                   2008.0                 121.0
36                   2001.0                  15.0
37                   1987.0                  69.0
38                   1988.0                   9.0
42                   2006.0                  52.0
44                   1999.0                  23.0
47                   2003.0                  73.0
66                   1991.0                  78.0
69                   1987.0                 163.0
74                   1991.0                  78.0
80                   1993.0                 168.0
84                   2001.0                  15.0
87                   1993.0                 125.0
89                   1997.0                  65.0
92                   1997.0                  86.0
93                   1997.0                 137.0
97                   1989.0                  55.0
100                  1989.0                  55.0
102                  1995.0                 133.0
106                  1987.0                 163.0
107                  1994.0                  28.0
110                  1992.0                  94.0
115                  1987.0                  37.0
116                  1991.0                 113.0
117                  1991.0                 132.0
120                  1987.0                 163.0
121                  1987.0                 227.0
126                  1991.0                  21.0
128                  1989.0                  55.0
137                  1987.0                  88.0
     RefersToDocumentNumber  RefersToDocumentYear
5                      98.0                2016.0
6                      97.0                1992.0
10                     84.0                2013.0
11                    199.0                2002.0
17                    130.0                2015.0
19                     94.0                2015.0
20                    100.0                2010.0
24                    144.0                2013.0
26                    115.0                2005.0
27                     84.0                2013.0
33                    121.0                2008.0
36                     15.0                2001.0
37                     69.0                1987.0
38                      9.0                1988.0
42                     52.0                2006.0
44                     23.0                1999.0
47                     73.0                2003.0
66                     78.0                1991.0
69                    163.0                1987.0
74                     78.0                1991.0
80                    168.0                1993.0
84                     15.0                2001.0
87                    125.0                1993.0
89                     65.0                1997.0
92                     86.0                1997.0
93                    137.0                1997.0
97                     55.0                1989.0
100                    55.0                1989.0
102                   133.0                1995.0
106                   163.0                1987.0
107                    28.0                1994.0
110                    94.0                1992.0
115                    37.0                1987.0
116                   113.0                1991.0
117                   132.0                1991.0
120                   163.0                1987.0
121                   227.0                1987.0
126                    21.0                1991.0
128                    55.0                1989.0
137                    88.0                1987.0

In [10]:
df

,DocumentNumber,DocumentDate,DocumentType,RefersToDocumentNumber,RefersToDocumentYear,Remarks
0,27,8/16/2021,C,NaN,NaN,NaN
1,1,2/15/2021,T,8.0,2020.0,2020 0008-00
2,67,10/9/2020,A,NaN,NaN,NaN
3,157,10/9/2020,A,NaN,NaN,NaN
4,189,10/9/2020,J,NaN,NaN,NaN
...,...,...,...,...,...,...
141,227,8/28/1987,C,NaN,NaN,NaN
142,37,7/24/1987,J,NaN,NaN,NaN
143,69,7/24/1987,B,NaN,NaN,NaN
144,4,2/5/1985,T,10300.0,NaN,NaN
145,10300,3/30/1978,J,NaN,NaN,Case #10300

In [12]:
remove_docs = df.loc[df['DocumentType'].isin(['R','T']), 'RefersToDocumentNumber']

In [13]:
remove_docs

1          8.0
5         98.0
6         97.0
10        84.0
11       199.0
17       130.0
20       100.0
24       144.0
36        15.0
37        69.0
38         9.0
42        52.0
44        23.0
47        73.0
66        78.0
74        78.0
80       168.0
82         1.0
87       125.0
89        65.0
92        86.0
93       137.0
100       55.0
102      133.0
106      163.0
107       28.0
110       94.0
111        NaN
115       37.0
116      113.0
117      132.0
121      227.0
125        NaN
126       21.0
137       88.0
138        NaN
144    10300.0
Name: RefersToDocumentNumber, dtype: float64

In [14]:
df = df[~df['DocumentNumber'].isin(remove_docs)]

In [15]:
df

,DocumentNumber,DocumentDate,DocumentType,RefersToDocumentNumber,RefersToDocumentYear,Remarks
0,27,8/16/2021,C,NaN,NaN,NaN
2,67,10/9/2020,A,NaN,NaN,NaN
3,157,10/9/2020,A,NaN,NaN,NaN
4,189,10/9/2020,J,NaN,NaN,NaN
5,250,10/9/2020,R,98.0,2016.0,NaN
...,...,...,...,...,...,...
126,36,4/16/1991,R,21.0,1991.0,NaN
133,2,11/15/1990,B,NaN,NaN,NaN
136,10,7/18/1988,B,NaN,NaN,NaN
138,76,8/28/1987,R,NaN,NaN,NaN
144,4,2/5/1985,T,10300.0,NaN,NaN

In [16]:
df = df.reset_index(drop=True)

In [17]:
df

,DocumentNumber,DocumentDate,DocumentType,RefersToDocumentNumber,RefersToDocumentYear,Remarks
0,27,8/16/2021,C,NaN,NaN,NaN
1,67,10/9/2020,A,NaN,NaN,NaN
2,157,10/9/2020,A,NaN,NaN,NaN
3,189,10/9/2020,J,NaN,NaN,NaN
4,250,10/9/2020,R,98.0,2016.0,NaN
...,...,...,...,...,...,...
90,36,4/16/1991,R,21.0,1991.0,NaN
91,2,11/15/1990,B,NaN,NaN,NaN
92,10,7/18/1988,B,NaN,NaN,NaN
93,76,8/28/1987,R,NaN,NaN,NaN
94,4,2/5/1985,T,10300.0,NaN,NaN