In [1]:
nums = [1,4,7,12,23]

cumsum = []
total=0
for num in nums:
    total+=num
    cumsum.append(total)
print(cumsum)

[1, 5, 12, 24, 47]

In [2]:
def invert(d):
    inverted = {}
    for key, value in d.items():
        inverted[value] = key
    return inverted
d = {'a':1,'b':2,'c':3,'d':4}
invert(d)

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}

In [5]:
import numpy as np
A = np.random.rand(3,3)
b = np.random.rand(3,)
x = np.linalg.solve(A,b)
print(x)

[ 2.8193242  -2.02873094 -1.65426975]

In [9]:
class Date:
    def __init__(self, month, day, year):
        if not (1 <= month <= 12):
            raise ValueError('Invalid month')
        if not (1 <= day <= 31):
            raise ValueError('Invalid day')
        self.month = month
        self.day = day
        self.year = year

    def format_numeric(self):
        return f"{self.month}/{self.day}/{self.year}"

    def format_long(self):
        months = [
            'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'
        ]
        return f"{months[int(self.month - 1)]} {self.day} {self.year}"
    def format_day_first(self):
        months = [
            'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'
        ]
        return f"{self.day} {months[int(self.month - 1)]} {self.year}"

    try:
        date = Date(12,25,2025)

        print(format_numeric())
        print(format_long())
        print(format_day_first())

    except:
        print("Error")

Error

In [12]:
import pandas as pd

df = pd.read_csv('TestMax.csv')
df.head()

   Unnamed: 0  Year1  Max1  Max2  Max3
0           0   2001    10   101    87
1           1   2002   103    19    88
2           2   2003    21    23    89
3           3   2004    27    28    91

In [33]:
import pandas as pd

df = pd.read_csv('TestMax.csv')
df['Max_value']=df[['Max1', 'Max2', 'Max3']].max(axis=1)
df_new = df[['Year1', 'Max_value']]
df_new

   Year1  Max_value
0   2001        101
1   2002        103
2   2003         89
3   2004         91

In [34]:
def nimadir(name, surname):
    pass
nimadir(surname='Baurjan', name='Davidov')

In [45]:
l1 = [2,4,3]
l2 = [5,6,4]
num=0
for i in range(0,len(l1)):
    num=l1[i]*10**i+num
num2 = 0
for i in range(0, len(l2)):
    num2=l2[i]*10**i+num2
result = num+num2
result

finals = []
for i in range(result):

807

In [2]:
import pandas as pd
df1 = pd.read_csv('TestMax.csv')
df1

   Unnamed: 0  Year1  Max1  Max2  Max3
0           0   2001    10   101    87
1           1   2002   103    19    88
2           2   2003    21    23    89
3           3   2004    27    28    91

In [6]:
df1['Max_value']=df1[['Max1', 'Max2', 'Max3']].max(axis=1)
df1

   Unnamed: 0  Year1  Max1  Max2  Max3  Max_value
0           0   2001    10   101    87        101
1           1   2002   103    19    88        103
2           2   2003    21    23    89         89
3           3   2004    27    28    91         91

In [13]:
dfnew = df1[['Year1', 'Max_value']]
dfnew

   Year1  Max_value
0   2001        101
1   2002        103
2   2003         89
3   2004         91

In [18]:
import random
import numpy as np
A = np.random.rand(3,3)
b = np.random.rand(3,1)
x = np.linalg.solve(A,b)
x

array([[ 1.3369161 ],
       [-0.36175285],
       [ 0.23641652]])