In [8]:
number = int(input("Enter a positive integer number: "))
def is_prime(number):
    if number<=1:
        return False
    for i in range(2, number):
        if number % i == 0:
            return False
        else:
            return True
print(is_prime(number))

True

In [9]:
def generate_primes(limit):
    primes = []
    for n in range(2, limit + 1):
        is_prime = True
        for i in range(2, int(n ** 0.5) + 1):
            if n % i == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(n)
    return primes


limit = int(input("Yuqori chegara sifatida musbat butun son kiriting: "))
print(generate_primes(limit))

[2, 3, 5, 7, 11, 13, 17, 19]

In [13]:
from collections import Counter
nums =  [1,2,2,3,3,3]
Counts = Counter(nums)
print(Counts)

Counter({3: 3, 2: 2, 1: 1})

In [98]:
nums =  [1,2,3,2,3,3,3,4,5,5,5,5,5]
dict = {}
setted_nums = set(nums)
for i in setted_nums:
    dict[i] = 0
for n in nums:
    dict[n] += 1
dict[2]

2

In [27]:
ls = ['red','blue','yellow','blue','red','yellow','red','blue']
dict = {}
setted_ls = set(ls)
for i in setted_ls:
    dict[i] = 0
for n in ls:
    dict[n] += 1
dict

{'red': 3, 'yellow': 2, 'blue': 3}

In [33]:
def ranged_primes(n,m):
    primes = []
    for i in range(n,m):
        is_prime = True
        for j in range(2, int(i ** 0.5) + 1):
            if i % j == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(i)
    return primes
print(ranged_primes(25,50))

[29, 31, 37, 41, 43, 47]

In [48]:
example = "a!1b@2c"
lettersnums = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
reversed = ''
puncs = {}
for i in range(len(example)):
    if example[i]  in lettersnums:

        reversed += example[i]
    else:
        puncs[i]=example[i]
reversed = reversed[::-1]
new_list=[]
for i in range(len(reversed)):
    new_list.append(reversed[i])
for n in puncs.keys():

    new_list.insert(n, puncs[n])
new_string = ''.join(new_list)
new_string

'c!2b@1a'

In [1]:
def get_permutations(new_word):
    if len(new_word) ==0:
        return [""]
    if len(new_word) ==1:
        return [new_word]
    perm = []
    for i in range(len(new_word)):
        current_char = new_word[i]
        remaining_char = new_word[:i] + new_word[i+1:]
        for p in get_permutations(remaining_char):
            perm.append(current_char + p)
    return perm
get_permutations("abc")
remaining_char

['abc', 'acb', 'bac', 'bca', 'cab', 'cba']

Generate all unique permutations of the input string and print each permutation on a separate line.

In [ ]:
from itertools import permutations

s = input().strip()

for p in permutations(s):
    print(''.join(p))

In [2]:
import pandas as pd
recipe = pd.DataFrame({
    "recipe_name": ["hotdog","hotdog","pilov","pilov","pilov","pizza","pizza","pizza"],
    "ingredient_id": [1,2,3,4,5,6,7,8],
    "ingredient_name": ["sausage","bread","rice","carrot","meat","flour","tomato","cheese"]
})

fridge = pd.DataFrame({
    "ingredient_id": [1,2,3,4,6],
    "ingredient_name": ["sausage","bread","rice","carrot","flour"]
})

recipe_ingredients = recipe.groupby("recipe_name")["ingredient_id"].apply(set)
fridge_ingredients = set(fridge["ingredient_id"])

available_recipes = [name for name, ingredients in recipe_ingredients.items() if
                     ingredients.issubset(fridge_ingredients)]

print(available_recipes)

['hotdog']

In [3]:
class Book:
    def __init__(self, title, author, is_borrowed=False):
        self.title = title
        self.author = author
        self.is_borrowed = is_borrowed
    def __str__(self):
        return f"Book(title={self.title!r}, author={self.author!r}, is_borrowed={self.is_borrowed})"
class Library:
    def __init__(self):
        self.books = []
    def add_book(self, book):
        self.books.append(book)
    def borrow_book(self, title):
        for book in self.books:
            if book.title == title:
                if not book.is_borrowed:
                    book.is_borrowed = True
                    return "Kitob ijaraga berildi"
                return "Kitob band"
        return "Mavjud emas"
    def return_book(self):
        for book in self.books:
            if book.is_borrowed:
                book.is_borrowed = False
                return "Kitob qaytarildi"
        return "Mavjud emas"
    def search_by_author(self, author):
        return[book for book in self.books if book.author == author]

In [ ]:
class Book:
    def __init__(self, title, author, is_borrowed=False):
        self.title = title
        self.author = author
        self.is_borrowed = is_borrowed

    def __repr__(self):
        return f"Book(title={self.title!r}, author={self.author!r}, is_borrowed={self.is_borrowed})"


class Library:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)

    def borrow_book(self, title):
        for book in self.books:
            if book.title == title:
                if not book.is_borrowed:
                    book.is_borrowed = True
                    return "Kitob ijaraga berildi"
                return "Kitob band"
        return "Mavjud emas"

    def return_book(self, title):
        for book in self.books:
            if book.title == title:
                book.is_borrowed = False
                return "Kitob qaytarildi"
        return "Mavjud emas"

    def search_by_author(self, author):
        return [book for book in self.books if book.author == author]

In [29]:
import json
import csv

def flatten(obj, parent_key="", sep="."):
    items = {}
    for k, v in obj.items():
        new_key = parent_key + sep + k if parent_key else k
        if isinstance(v, dict):
            items.update(flatten(v, new_key, sep=sep))
        elif isinstance(v, list):
            items[new_key] = ", ".join(str(i) for i in v)
        else:
            items[new_key] = v
    return items

with open('student (4).json', 'r') as json_file:
    data = json.load(json_file)

flat_data = [flatten(row) for row in data["Students"]]

fieldnames = list(flat_data[0].keys())

with open('student.csv', 'w', newline="") as csv_file:
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(flat_data)
with open('student.csv', 'r') as csv_file:
    reader = csv.reader(csv_file)
    for row in reader:
        print(row)

['ID', 'Name', 'Age']
['1', 'Alex', '21']
['2', 'Sara', '23']
['3', 'John', '28']
['4', 'David', '26']
['5', 'Josh', '28']

In [32]:
import json
import csv
with open('student (4).json', 'r') as json_file:
    data = json.load(json_file)
fieldnames = list(data["Students"][0].keys())
with open('student.csv', 'w', newline="") as csv_file:
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(data['Students'])
with open('student.csv', 'r') as csv_file:
    reader = csv.reader(csv_file)
    for row in reader:
        print(row)

['ID', 'Name', 'Age']
['1', 'Alex', '21']
['2', 'Sara', '23']
['3', 'John', '28']
['4', 'David', '26']
['5', 'Josh', '28']

In [12]:
data

{'Students': [{'ID': 1, 'Name': 'Alex', 'Age': 21},
  {'ID': 2, 'Name': 'Sara', 'Age': 23},
  {'ID': 3, 'Name': 'John', 'Age': 28},
  {'ID': 4, 'Name': 'David', 'Age': 26},
  {'ID': 5, 'Name': 'Josh', 'Age': 28}]}

In [13]:
print([1,2]+[3,4])

[1, 2, 3, 4]

In [14]:
num = 18
ans = ""
if num>=18:
  ans+='You are an adult'
if num<=60:
  ans+='You are working age'
print(ans)

You are an adultYou are working age

In [15]:
a, b = 0, 1
a, b = b, a + b
print(a,b)

1 1

In [33]:
import numpy as np
data = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(data.max(axis=0))

[5 6]

In [40]:
with open('employee_data (2).csv', 'r') as file:
    data = csv.DictReader(file)
    for row in data:
        print(row)

{'EmpID': '1', 'EmpName': 'Cathy Reeves', 'BirthDate': '1975-12-25', 'HireDate': '2013-01-08', 'DepartmentID': '101', 'Salary': '104666.75', 'Birth_Country': 'USA'}
{'EmpID': '2', 'EmpName': 'William Ward', 'BirthDate': '1972-01-01', 'HireDate': '2009-10-23', 'DepartmentID': '105', 'Salary': '79245.98', 'Birth_Country': 'Germany'}
{'EmpID': '3', 'EmpName': 'Kevin Moore', 'BirthDate': '1992-08-26', 'HireDate': '2022-09-12', 'DepartmentID': '105', 'Salary': '32528.41', 'Birth_Country': 'Germany'}
{'EmpID': '4', 'EmpName': 'Jason Young', 'BirthDate': '1964-08-08', 'HireDate': '2008-04-01', 'DepartmentID': '105', 'Salary': '83259.5', 'Birth_Country': 'India'}
{'EmpID': '5', 'EmpName': 'Angela Brown', 'BirthDate': '1965-07-18', 'HireDate': '2005-06-22', 'DepartmentID': '103', 'Salary': '114796.51', 'Birth_Country': 'Germany'}
{'EmpID': '6', 'EmpName': 'Lisa Brown DVM', 'BirthDate': '1972-09-24', 'HireDate': '2020-07-26', 'DepartmentID': '104', 'Salary': '88253.26', 'Birth_Country': 'Germany'}
{'EmpID': '7', 'EmpName': 'Raymond Turner', 'BirthDate': '1975-01-15', 'HireDate': '2014-01-25', 'DepartmentID': '103', 'Salary': '63516.53', 'Birth_Country': 'USA'}
{'EmpID': '8', 'EmpName': 'Linda Bolton', 'BirthDate': '1993-07-02', 'HireDate': '2006-08-28', 'DepartmentID': '104', 'Salary': '31675.85', 'Birth_Country': 'India'}
{'EmpID': '9', 'EmpName': 'Christopher Nguyen', 'BirthDate': '2001-08-03', 'HireDate': '2017-09-17', 'DepartmentID': '103', 'Salary': '75448.89', 'Birth_Country': 'India'}
{'EmpID': '10', 'EmpName': 'Yvonne Webster', 'BirthDate': '1971-03-27', 'HireDate': '2009-08-28', 'DepartmentID': '105', 'Salary': '40245.38', 'Birth_Country': 'USA'}
{'EmpID': '11', 'EmpName': 'Sandra Beck', 'BirthDate': '1998-07-03', 'HireDate': '2022-06-16', 'DepartmentID': '103', 'Salary': '111337.15', 'Birth_Country': 'USA'}
{'EmpID': '12', 'EmpName': 'Donald Snow', 'BirthDate': '1999-03-10', 'HireDate': '2008-01-20', 'DepartmentID': '102', 'Salary': '105739.53', 'Birth_Country': 'UK'}
{'EmpID': '13', 'EmpName': 'Stephen Owen', 'BirthDate': '1990-10-20', 'HireDate': '2015-01-26', 'DepartmentID': '101', 'Salary': '32302.38', 'Birth_Country': 'UK'}
{'EmpID': '14', 'EmpName': 'Matthew Holmes PhD', 'BirthDate': '1976-03-04', 'HireDate': '2016-01-04', 'DepartmentID': '105', 'Salary': '60356.01', 'Birth_Country': 'Germany'}
{'EmpID': '15', 'EmpName': 'Deborah Cortez', 'BirthDate': '1993-12-15', 'HireDate': '2019-03-04', 'DepartmentID': '105', 'Salary': '100070.64', 'Birth_Country': 'India'}
{'EmpID': '16', 'EmpName': 'John Craig', 'BirthDate': '2000-01-15', 'HireDate': '2017-12-18', 'DepartmentID': '104', 'Salary': '90916.0', 'Birth_Country': 'Germany'}
{'EmpID': '17', 'EmpName': 'Sheri Walker', 'BirthDate': '1981-12-28', 'HireDate': '2023-12-08', 'DepartmentID': '104', 'Salary': '75808.56', 'Birth_Country': 'India'}
{'EmpID': '18', 'EmpName': 'Douglas Griffin', 'BirthDate': '1992-07-29', 'HireDate': '2021-05-21', 'DepartmentID': '101', 'Salary': '35759.07', 'Birth_Country': 'UK'}
{'EmpID': '19', 'EmpName': 'Kelsey Banks', 'BirthDate': '1967-02-19', 'HireDate': '2021-01-25', 'DepartmentID': '104', 'Salary': '56245.27', 'Birth_Country': 'USA'}
{'EmpID': '20', 'EmpName': 'Morgan Boyle', 'BirthDate': '1988-10-22', 'HireDate': '2015-08-26', 'DepartmentID': '102', 'Salary': '78062.83', 'Birth_Country': 'Germany'}
{'EmpID': '21', 'EmpName': 'Richard Rice', 'BirthDate': '1964-04-11', 'HireDate': '2024-09-15', 'DepartmentID': '104', 'Salary': '92851.77', 'Birth_Country': 'UK'}
{'EmpID': '22', 'EmpName': 'Gregory Rodriguez', 'BirthDate': '1966-10-11', 'HireDate': '2023-12-24', 'DepartmentID': '102', 'Salary': '77922.92', 'Birth_Country': 'India'}
{'EmpID': '23', 'EmpName': 'Eddie James', 'BirthDate': '1966-08-08', 'HireDate': '2016-12-02', 'DepartmentID': '103', 'Salary': '50192.6', 'Birth_Country': 'Germany'}
{'EmpID': '24', 'EmpName': 'Robert Foster', 'BirthDate': '1976-11-26', 'HireDate': '2006-06-17', 'DepartmentID': '102', 'Salary': '58975.31', 'Birth_Country': 'UK'}
{'EmpID': '25', 'EmpName': 'Francisco Lee', 'BirthDate': '1968-06-17', 'HireDate': '2024-09-13', 'DepartmentID': '105', 'Salary': '57429.59', 'Birth_Country': 'India'}
{'EmpID': '26', 'EmpName': 'Andrea Turner', 'BirthDate': '1967-05-05', 'HireDate': '2018-08-15', 'DepartmentID': '102', 'Salary': '34639.15', 'Birth_Country': 'India'}
{'EmpID': '27', 'EmpName': 'Eric Atkins', 'BirthDate': '1982-06-05', 'HireDate': '2010-06-29', 'DepartmentID': '102', 'Salary': '75420.44', 'Birth_Country': 'Germany'}
{'EmpID': '28', 'EmpName': 'Patrick Hart', 'BirthDate': '1994-12-09', 'HireDate': '2016-09-14', 'DepartmentID': '101', 'Salary': '51003.93', 'Birth_Country': 'India'}
{'EmpID': '29', 'EmpName': 'Rebecca Brown', 'BirthDate': '1985-02-21', 'HireDate': '2010-08-17', 'DepartmentID': '101', 'Salary': '66173.95', 'Birth_Country': 'Germany'}
{'EmpID': '30', 'EmpName': 'Joseph Reynolds', 'BirthDate': '1989-09-28', 'HireDate': '2005-09-24', 'DepartmentID': '102', 'Salary': '80431.53', 'Birth_Country': 'UK'}
{'EmpID': '31', 'EmpName': 'Jessica Palmer', 'BirthDate': '1996-10-29', 'HireDate': '2010-01-06', 'DepartmentID': '103', 'Salary': '117050.58', 'Birth_Country': 'UK'}
{'EmpID': '32', 'EmpName': 'Elizabeth Alexander', 'BirthDate': '1970-04-29', 'HireDate': '2005-12-29', 'DepartmentID': '103', 'Salary': '59738.17', 'Birth_Country': 'India'}
{'EmpID': '33', 'EmpName': 'Danielle Dickerson', 'BirthDate': '1996-02-12', 'HireDate': '2014-03-30', 'DepartmentID': '103', 'Salary': '67723.97', 'Birth_Country': 'UK'}
{'EmpID': '34', 'EmpName': 'Todd Watson', 'BirthDate': '1973-11-02', 'HireDate': '2016-03-26', 'DepartmentID': '101', 'Salary': '57074.33', 'Birth_Country': 'Germany'}
{'EmpID': '35', 'EmpName': 'Wayne Prince', 'BirthDate': '1988-03-27', 'HireDate': '2015-12-12', 'DepartmentID': '105', 'Salary': '42146.52', 'Birth_Country': 'India'}
{'EmpID': '36', 'EmpName': 'Linda Clark', 'BirthDate': '1996-09-02', 'HireDate': '2010-05-07', 'DepartmentID': '102', 'Salary': '48136.64', 'Birth_Country': 'Germany'}
{'EmpID': '37', 'EmpName': 'Adam Fitzpatrick', 'BirthDate': '2002-06-13', 'HireDate': '2010-03-12', 'DepartmentID': '103', 'Salary': '63815.8', 'Birth_Country': 'Germany'}
{'EmpID': '38', 'EmpName': 'Laura Williams', 'BirthDate': '2000-08-03', 'HireDate': '2011-02-19', 'DepartmentID': '102', 'Salary': '48520.19', 'Birth_Country': 'USA'}
{'EmpID': '39', 'EmpName': 'Christine Williams', 'BirthDate': '1994-10-19', 'HireDate': '2020-01-02', 'DepartmentID': '105', 'Salary': '112393.55', 'Birth_Country': 'USA'}
{'EmpID': '40', 'EmpName': 'Kelly Love', 'BirthDate': '1998-04-23', 'HireDate': '2010-09-05', 'DepartmentID': '104', 'Salary': '75365.39', 'Birth_Country': 'UK'}
{'EmpID': '41', 'EmpName': 'Sheila Cooper', 'BirthDate': '1974-01-20', 'HireDate': '2021-01-05', 'DepartmentID': '103', 'Salary': '43353.72', 'Birth_Country': 'UK'}
{'EmpID': '42', 'EmpName': 'Thomas Holmes', 'BirthDate': '1975-06-16', 'HireDate': '2010-03-17', 'DepartmentID': '101', 'Salary': '101953.27', 'Birth_Country': 'India'}
{'EmpID': '43', 'EmpName': 'Jamie Parker', 'BirthDate': '1968-02-20', 'HireDate': '2023-04-12', 'DepartmentID': '105', 'Salary': '70615.71', 'Birth_Country': 'UK'}
{'EmpID': '44', 'EmpName': 'Hannah Williamson', 'BirthDate': '1986-04-16', 'HireDate': '2017-05-06', 'DepartmentID': '103', 'Salary': '98521.71', 'Birth_Country': 'India'}
{'EmpID': '45', 'EmpName': 'Kristy Norton', 'BirthDate': '1978-06-13', 'HireDate': '2019-07-09', 'DepartmentID': '102', 'Salary': '109640.55', 'Birth_Country': 'UK'}
{'EmpID': '46', 'EmpName': 'Jessica Brown', 'BirthDate': '1984-09-11', 'HireDate': '2007-01-21', 'DepartmentID': '101', 'Salary': '101468.12', 'Birth_Country': 'Germany'}
{'EmpID': '47', 'EmpName': 'Deanna Mitchell', 'BirthDate': '1970-04-28', 'HireDate': '2012-10-19', 'DepartmentID': '101', 'Salary': '92689.06', 'Birth_Country': 'India'}
{'EmpID': '48', 'EmpName': 'Christine Jensen', 'BirthDate': '1964-10-25', 'HireDate': '2008-10-19', 'DepartmentID': '105', 'Salary': '102135.87', 'Birth_Country': 'Germany'}
{'EmpID': '49', 'EmpName': 'Jacob Jimenez', 'BirthDate': '1994-11-24', 'HireDate': '2023-11-25', 'DepartmentID': '102', 'Salary': '77628.89', 'Birth_Country': 'USA'}
{'EmpID': '50', 'EmpName': 'Isaac Young', 'BirthDate': '1991-09-10', 'HireDate': '2011-01-01', 'DepartmentID': '104', 'Salary': '69160.42', 'Birth_Country': 'USA'}

In [41]:
row

{'EmpID': '50',
 'EmpName': 'Isaac Young',
 'BirthDate': '1991-09-10',
 'HireDate': '2011-01-01',
 'DepartmentID': '104',
 'Salary': '69160.42',
 'Birth_Country': 'USA'}

In [46]:
import pandas as pd
df = pd.read_csv('employee_data (2).csv')
df

,EmpID,EmpName,BirthDate,HireDate,DepartmentID,Salary,Birth_Country
0,1,Cathy Reeves,1975-12-25,2013-01-08,101,104666.75,USA
1,2,William Ward,1972-01-01,2009-10-23,105,79245.98,Germany
2,3,Kevin Moore,1992-08-26,2022-09-12,105,32528.41,Germany
3,4,Jason Young,1964-08-08,2008-04-01,105,83259.50,India
4,5,Angela Brown,1965-07-18,2005-06-22,103,114796.51,Germany
5,6,Lisa Brown DVM,1972-09-24,2020-07-26,104,88253.26,Germany
6,7,Raymond Turner,1975-01-15,2014-01-25,103,63516.53,USA
7,8,Linda Bolton,1993-07-02,2006-08-28,104,31675.85,India
8,9,Christopher Nguyen,2001-08-03,2017-09-17,103,75448.89,India
9,10,Yvonne Webster,1971-03-27,2009-08-28,105,40245.38,USA
10,11,Sandra Beck,1998-07-03,2022-06-16,103,111337.15,USA
11,12,Donald Snow,1999-03-10,2008-01-20,102,105739.53,UK
12,13,Stephen Owen,1990-10-20,2015-01-26,101,32302.38,UK
13,14,Matthew Holmes PhD,1976-03-04,2016-01-04,105,60356.01,Germany
14,15,Deborah Cortez,1993-12-15,2019-03-04,105,100070.64,India
15,16,John Craig,2000-01-15,2017-12-18,104,90916.00,Germany
16,17,Sheri Walker,1981-12-28,2023-12-08,104,75808.56,India
17,18,Douglas Griffin,1992-07-29,2021-05-21,101,35759.07,UK
18,19,Kelsey Banks,1967-02-19,2021-01-25,104,56245.27,USA
19,20,Morgan Boyle,1988-10-22,2015-08-26,102,78062.83,Germany
20,21,Richard Rice,1964-04-11,2024-09-15,104,92851.77,UK
21,22,Gregory Rodriguez,1966-10-11,2023-12-24,102,77922.92,India
22,23,Eddie James,1966-08-08,2016-12-02,103,50192.60,Germany
23,24,Robert Foster,1976-11-26,2006-06-17,102,58975.31,UK
24,25,Francisco Lee,1968-06-17,2024-09-13,105,57429.59,India
25,26,Andrea Turner,1967-05-05,2018-08-15,102,34639.15,India
26,27,Eric Atkins,1982-06-05,2010-06-29,102,75420.44,Germany
27,28,Patrick Hart,1994-12-09,2016-09-14,101,51003.93,India
28,29,Rebecca Brown,1985-02-21,2010-08-17,101,66173.95,Germany
29,30,Joseph Reynolds,1989-09-28,2005-09-24,102,80431.53,UK
30,31,Jessica Palmer,1996-10-29,2010-01-06,103,117050.58,UK
31,32,Elizabeth Alexander,1970-04-29,2005-12-29,103,59738.17,India
32,33,Danielle Dickerson,1996-02-12,2014-03-30,103,67723.97,UK
33,34,Todd Watson,1973-11-02,2016-03-26,101,57074.33,Germany
34,35,Wayne Prince,1988-03-27,2015-12-12,105,42146.52,India
35,36,Linda Clark,1996-09-02,2010-05-07,102,48136.64,Germany
36,37,Adam Fitzpatrick,2002-06-13,2010-03-12,103,63815.80,Germany
37,38,Laura Williams,2000-08-03,2011-02-19,102,48520.19,USA
38,39,Christine Williams,1994-10-19,2020-01-02,105,112393.55,USA
39,40,Kelly Love,1998-04-23,2010-09-05,104,75365.39,UK
40,41,Sheila Cooper,1974-01-20,2021-01-05,103,43353.72,UK
41,42,Thomas Holmes,1975-06-16,2010-03-17,101,101953.27,India
42,43,Jamie Parker,1968-02-20,2023-04-12,105,70615.71,UK
43,44,Hannah Williamson,1986-04-16,2017-05-06,103,98521.71,India
44,45,Kristy Norton,1978-06-13,2019-07-09,102,109640.55,UK
45,46,Jessica Brown,1984-09-11,2007-01-21,101,101468.12,Germany
46,47,Deanna Mitchell,1970-04-28,2012-10-19,101,92689.06,India
47,48,Christine Jensen,1964-10-25,2008-10-19,105,102135.87,Germany
48,49,Jacob Jimenez,1994-11-24,2023-11-25,102,77628.89,USA
49,50,Isaac Young,1991-09-10,2011-01-01,104,69160.42,USA

In [49]:
USA = df[df['Birth_Country'] == 'USA']

In [51]:
USA.to_csv('USA.csv', index=False)

In [52]:
with open('USA.csv', 'r') as csv_file:
    reader = csv.reader(csv_file)
    for row in reader:
        print(row)

['EmpID', 'EmpName', 'BirthDate', 'HireDate', 'DepartmentID', 'Salary', 'Birth_Country']
['1', 'Cathy Reeves', '1975-12-25', '2013-01-08', '101', '104666.75', 'USA']
['7', 'Raymond Turner', '1975-01-15', '2014-01-25', '103', '63516.53', 'USA']
['10', 'Yvonne Webster', '1971-03-27', '2009-08-28', '105', '40245.38', 'USA']
['11', 'Sandra Beck', '1998-07-03', '2022-06-16', '103', '111337.15', 'USA']
['19', 'Kelsey Banks', '1967-02-19', '2021-01-25', '104', '56245.27', 'USA']
['38', 'Laura Williams', '2000-08-03', '2011-02-19', '102', '48520.19', 'USA']
['39', 'Christine Williams', '1994-10-19', '2020-01-02', '105', '112393.55', 'USA']
['49', 'Jacob Jimenez', '1994-11-24', '2023-11-25', '102', '77628.89', 'USA']
['50', 'Isaac Young', '1991-09-10', '2011-01-01', '104', '69160.42', 'USA']

In [53]:
Germany = df[df['Birth_Country'] == 'Germany']
Germany.to_csv('Germany.csv', index=False)

In [54]:
India = df[df['Birth_Country'] == 'India']
India.to_csv('India.csv', index=False)

In [55]:
UK = df[df['Birth_Country'] == 'UK']
UK.to_csv('UK.csv', index=False)

In [72]:
from datetime import datetime
now= datetime.now()
df['HireDate'] = pd.to_datetime(df['HireDate'])
df['Experience'] = now - df['HireDate']
df['Experience']
result = df.loc[df.groupby('Birth_Country')['Experience'].idxmax()]

In [73]:
result

,EmpID,EmpName,BirthDate,HireDate,DepartmentID,Salary,Birth_Country,Experience,most_experienced
4,5,Angela Brown,1965-07-18,2005-06-22,103,114796.51,Germany,7583 days 15:29:42.486501,NaN
31,32,Elizabeth Alexander,1970-04-29,2005-12-29,103,59738.17,India,7393 days 15:29:42.486501,NaN
29,30,Joseph Reynolds,1989-09-28,2005-09-24,102,80431.53,UK,7489 days 15:29:42.486501,NaN
9,10,Yvonne Webster,1971-03-27,2009-08-28,105,40245.38,USA,6055 days 15:29:42.486501,NaN

In [82]:
df['Average_salary'] = df.groupby('Birth_Country')['Salary'].transform('mean')

In [91]:
above_average = df[df['Salary'] > df['Average_salary']]

In [92]:
above_average

,EmpID,EmpName,BirthDate,HireDate,DepartmentID,Salary,Birth_Country,Experience,most_experienced,Average_salary,above_average_salary
0,1,Cathy Reeves,1975-12-25,2013-01-08,101,104666.75,USA,4826 days 15:29:42.486501,NaN,75968.236667,True
1,2,William Ward,1972-01-01,2009-10-23,105,79245.98,Germany,5999 days 15:29:42.486501,NaN,73905.116667,True
3,4,Jason Young,1964-08-08,2008-04-01,105,83259.50,India,6569 days 15:29:42.486501,NaN,70164.840000,True
4,5,Angela Brown,1965-07-18,2005-06-22,103,114796.51,Germany,7583 days 15:29:42.486501,NaN,73905.116667,True
5,6,Lisa Brown DVM,1972-09-24,2020-07-26,104,88253.26,Germany,2070 days 15:29:42.486501,NaN,73905.116667,True
8,9,Christopher Nguyen,2001-08-03,2017-09-17,103,75448.89,India,3113 days 15:29:42.486501,NaN,70164.840000,True
10,11,Sandra Beck,1998-07-03,2022-06-16,103,111337.15,USA,1380 days 15:29:42.486501,NaN,75968.236667,True
11,12,Donald Snow,1999-03-10,2008-01-20,102,105739.53,UK,6641 days 15:29:42.486501,NaN,74150.792500,True
14,15,Deborah Cortez,1993-12-15,2019-03-04,105,100070.64,India,2580 days 15:29:42.486501,NaN,70164.840000,True
15,16,John Craig,2000-01-15,2017-12-18,104,90916.00,Germany,3021 days 15:29:42.486501,NaN,73905.116667,True
16,17,Sheri Walker,1981-12-28,2023-12-08,104,75808.56,India,840 days 15:29:42.486501,NaN,70164.840000,True
19,20,Morgan Boyle,1988-10-22,2015-08-26,102,78062.83,Germany,3866 days 15:29:42.486501,NaN,73905.116667,True
20,21,Richard Rice,1964-04-11,2024-09-15,104,92851.77,UK,558 days 15:29:42.486501,NaN,74150.792500,True
21,22,Gregory Rodriguez,1966-10-11,2023-12-24,102,77922.92,India,824 days 15:29:42.486501,NaN,70164.840000,True
26,27,Eric Atkins,1982-06-05,2010-06-29,102,75420.44,Germany,5750 days 15:29:42.486501,NaN,73905.116667,True
29,30,Joseph Reynolds,1989-09-28,2005-09-24,102,80431.53,UK,7489 days 15:29:42.486501,NaN,74150.792500,True
30,31,Jessica Palmer,1996-10-29,2010-01-06,103,117050.58,UK,5924 days 15:29:42.486501,NaN,74150.792500,True
38,39,Christine Williams,1994-10-19,2020-01-02,105,112393.55,USA,2276 days 15:29:42.486501,NaN,75968.236667,True
39,40,Kelly Love,1998-04-23,2010-09-05,104,75365.39,UK,5682 days 15:29:42.486501,NaN,74150.792500,True
41,42,Thomas Holmes,1975-06-16,2010-03-17,101,101953.27,India,5854 days 15:29:42.486501,NaN,70164.840000,True
43,44,Hannah Williamson,1986-04-16,2017-05-06,103,98521.71,India,3247 days 15:29:42.486501,NaN,70164.840000,True
44,45,Kristy Norton,1978-06-13,2019-07-09,102,109640.55,UK,2453 days 15:29:42.486501,NaN,74150.792500,True
45,46,Jessica Brown,1984-09-11,2007-01-21,101,101468.12,Germany,7005 days 15:29:42.486501,NaN,73905.116667,True
46,47,Deanna Mitchell,1970-04-28,2012-10-19,101,92689.06,India,4907 days 15:29:42.486501,NaN,70164.840000,True
47,48,Christine Jensen,1964-10-25,2008-10-19,105,102135.87,Germany,6368 days 15:29:42.486501,NaN,73905.116667,True
48,49,Jacob Jimenez,1994-11-24,2023-11-25,102,77628.89,USA,853 days 15:29:42.486501,NaN,75968.236667,True

In [100]:
import numpy as np
import math
word = 'abc'
permuted = []
for i in range(len(word)):
    for j in range(i+1, len(word)+1):
        permuted.append(word[i:j])
permuted

['a', 'ab', 'abc', 'b', 'bc', 'c']

In [104]:
word = 'abc'
permuted = []
for i in range(len(word)):
    current_char = word[i]
    remaining_char = word[:i] + word[i+1:]
    for j in range(len(word)-1):
        if i<j:

         permuted.append(current_char + j)
permuted

['ab', 'ac', 'ba', 'bc', 'ca', 'cb']

In [6]:
def digit_sum(k):
    sum = 0
    while k > 0:
        sum += k % 10
        k //= 10
    return sum
digit_sum(27)

9

In [10]:
def is_prime(n):
    if n < 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True
is_prime(1)

True

Create a new SQLite database and define a `Roster` table with these columns:
- `Name` as text
- `Species` as text
- `Age` as integer

In [11]:
import sqlite3

conn = sqlite3.connect('roster.db')
cursor = conn.cursor()

cursor.execute("""
                create table if not exists Roster(
                     Name text,
                     Species text,
                     Age integer
                 )

""")

In [12]:
cursor.executemany(
    "INSERT INTO Roster (Name, Species, Age) VALUES (?, ?, ?)",
    [
        ("Benjamin Sisko", "Human", 40),
        ("Jadzia Dax", "Trill", 300),
        ("Kira Nerys", "Bajoran", 29),
    ],
)
conn.commit()

In [16]:
cursor.execute("""
Select * from Roster
""")
print(cursor.fetchall())

[('Benjamin Sisko', 'Human', 40), ('Jadzia Dax', 'Trill', 300), ('Kira Nerys', 'Bajoran', 29)]

In [15]:
cursor.execute("""
Select Name, Age from Roster where Species = 'Bajoran'
""")
rows = cursor.fetchall()
for row in rows:
    print(rows)

[('Kira Nerys', 29)]

In [24]:
import json
with open('employees.json', 'r') as json_file:
    data = json.load(json_file)
print(data)

new_employee = {
    "id": int(input('Enter Employee ID: ')),
    "name": input('Enter Name: '),
    "role": input('Enter role: '),
    "department": input('Enter department: '),
    "salary": float(input('Enter salary: '))
}

data['employees'].append(new_employee)

with open('employees.json', 'w') as json_file:
    json.dump(data, json_file, indent=4)

{'employees': [{'id': 1, 'name': 'Alice', 'role': 'Developer', 'department': 'IT', 'salary': 5000}, {'id': 2, 'name': 'Bob', 'role': 'Manager', 'department': 'HR', 'salary': 7000}], 'id': 7, 'name': 'Baurjan', 'role': 'ad', 'department': 'hr', 'salary': 5600.0}

In [25]:
with open('employees.json', 'r') as json_file:
    data = json.load(json_file)
print(data)

{'employees': [{'id': 1, 'name': 'Alice', 'role': 'Developer', 'department': 'IT', 'salary': 5000}, {'id': 2, 'name': 'Bob', 'role': 'Manager', 'department': 'HR', 'salary': 7000}, {'id': 7, 'name': 'orif', 'role': 'teacher', 'department': 'teachers', 'salary': 5800.0}], 'id': 7, 'name': 'Baurjan', 'role': 'ad', 'department': 'hr', 'salary': 5600.0}

In [47]:
import pandas as pd
df = pd.read_csv('customer_orders.csv')
df['filtered_df'] = df.groupby('CustomerID')['Quantity'].transform('sum')
df = df[df['filtered_df'] > 20]
df.drop(df[df['filtered_df'] < 20].index, inplace=True)
df

    OrderID  CustomerID              Product  Quantity  Price  filtered_df
0         1         101               Laptop         2    800           27
1         2         102           Headphones         1    150           25
2         3         103           Smartphone         3    400           28
3         4         101  External Hard Drive         2     80           27
4         5         102             Backpack         1     40           25
..      ...         ...                  ...       ...    ...          ...
95       96         103              Blender         1     60           28
96       97         104          Sport Shoes         2     40           27
97       98         105        Comforter Set         1     45           21
98       99         101     Wireless Earbuds         2    120           27
99      100         102       Gaming Console         1    400           25

[100 rows x 6 columns]

In [49]:
import pandas as pd
df = pd.DataFrame({
    "receipt_no": [1001,1002,1003,1004,1006,1006,1007,1008,1009,1010],
    "amount":     [  10,  15,  20,   5,  50,  50,  10,  25,  30,  40]
})
missing_receipts = sorted(set(range(df["receipt_no"].min(), df["receipt_no"].max() + 1)) - set(df["receipt_no"]))
missing_receipts

[1005]

In [50]:
print(range(df['receipt_no'].min(), df['receipt_no'].max() + 1))

range(1001, 1011)

In [51]:
set(df['receipt_no'])

{1001, 1002, 1003, 1004, 1006, 1007, 1008, 1009, 1010}

In [52]:
set(range(df['receipt_no'].min(), df['receipt_no'].max() + 1))

{1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010}

In [53]:
set(range(df['receipt_no'].min(), df['receipt_no'].max() + 1))-set(df['receipt_no'])

{1005}

In [66]:
numbs = [1,2,3,1]
setted = set(numbs)
if len(setted) == len(numbs):
    print('False')
else:
    print('True')

True

In [63]:
len(setted)

{1, 2, 3, 4}

3

In [1]:
x = [1,2,3]
print(x[3])

IndexError: list index out of range

In [2]:
x = (1,2,3)
x[0] = 5

TypeError: 'tuple' object does not support item assignment

In [3]:
x = [1, 2, 3]
y = x
y.append(4)
print(x)

[1, 2, 3, 4]

In [4]:
d = {"a": 1}
print(d.get("b", 10))

10

In [5]:
def f(x=[]):
    x.append(1)
    return x

print(f())
print(f())

[1]
[1, 1]

In [6]:
try:
    print("A")
    x = 1 / 0
except ZeroDivisionError:
    print("B")
finally:
    print("C")

A
B
C

In [7]:
import pandas as pd
s = pd.Series([10, 20, 30], index=["a", "b", "c"])
print(s["b"])

20

In [8]:
import json
x = '{"a": 1, "b": 2}'
data = json.loads(x)
print(type(data))

<class 'dict'>

In [14]:
import pandas as pd

df = pd.DataFrame({
    "name": [" ali", "BOB ", "  Charlie ", None],
    "department": ["IT", "HR", "IT", "Finance"]
})
df['name'] = df['name'].str.strip()
df['name'] = df['name'].str.lower()
df['name'] = df['name'].str.capitalize()

In [22]:
import pandas as pd

df = pd.DataFrame({
    "employee": ["Ali", "Vali", "Sara", "Tom", "Lola", "John"],
    "department": ["IT", "IT", "HR", "HR", "Finance", "Finance"],
    "salary": [1200, 900, 1500, 1300, 1000, 1700]
})
df['average_salary'] = df.groupby('department')['salary'].transform('mean')
result = df[df['salary'] > df['average_salary']]
result

In [75]:
import pandas as pd

df1 = pd.DataFrame({
    "age": ["25", "30", "unknown", None, "41"],
    "score": ["88.5", "91", "absent", "77", None]
})
df1['age'] = pd.to_numeric(df1['age'], errors='coerce')
df1['score'] = pd.to_numeric(df1['score'], errors='coerce')
df1['avg_age'] = df1['age'].mean()
df1['avg_score'] = df1['score'].mean()
df1

In [86]:
data = {
    "employees": [
        {"id": 1, "name": "Ali", "info": {"city": "Tashkent", "age": 25}},
        {"id": 2, "name": "Sara", "info": {"city": "Samarkand", "age": 28}},
        {"id": 3, "name": "Tom", "info": {"city": "Bukhara", "age": 31}}
    ]
}
import pandas as pd
df2 = pd.json_normalize(data['employees'])
df2

   id  name  info.city  info.age
0   1   Ali   Tashkent        25
1   2  Sara  Samarkand        28
2   3   Tom    Bukhara        31

In [88]:
import pandas as pd

df3 = pd.DataFrame({
    "receipt_no": [1001, 1002, 1003, 1005, 1006, 1008]
})
missing_values = sorted(set(range(df3["receipt_no"].min(), df3["receipt_no"].max() + 1)) - set(df3["receipt_no"]))
missing_values

In [98]:
def count_even_odd(nums):
    even_count = 0
    odd_count = 0
    for num in nums:
        if num % 2 ==0:
            even_count += 1
        else:
            odd_count += 1
    return even_count, odd_count
count_even_odd([1,2,3,4,5,6,7,8,9,10])

(5, 5)

In [100]:
word = 'hello'
reversed_word = ''
for char in word:
    reversed_word = char + reversed_word
reversed_word

'olleh'

In [102]:
def find_max(nums):
    max_num = nums[0]
    for num in nums:
        if num > max_num:
            max_num = num
    return max_num
find_max([2,3,5,6,4,3,2,2,6])

6

In [117]:
def check_palindrome(word):
    reversed_word = ''
    for char in word:
        reversed_word = char + reversed_word
    return word == reversed_word
check_palindrome('racecar')

True

In [118]:
a=0
b=1
for i in range(5):
    c=a+b
    a=b
    b=c
    print(c)

1
2
3
5
8

In [1]:
a, b = 0, 1
a, b = b, a + b
print(a,b)

1 1

In [2]:
def f():
    return 5
print(f())

5